=== hannaat/tugas-xml-dan-dtd/hotel.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT hotel (Kamar)+>
<!ATTLIST hotel
    xmlns CDATA #FIXED ''>

<!ELEMENT Kamar (kode,lantai,harga,fasilitas,jenis_kamar)>
<!ATTLIST Kamar
    xmlns CDATA #FIXED ''>

<!ELEMENT kode (#PCDATA)>
<!ATTLIST kode
    xmlns CDATA #FIXED ''>

<!ELEMENT lantai (#PCDATA)>
<!ATTLIST lantai
    xmlns CDATA #FIXED ''>

<!ELEMENT harga (#PCDATA)>
<!ATTLIST harga
    xmlns CDATA #FIXED ''>

<!ELEMENT fasilitas (AC,kamar_mandi,TV,tempat_tidur,sofa?,meja,
                     (pengering_rambut,mesin_pembuat_kopi)?,ruang_tamu?,
                     ukuran_ruangan)>
<!ATTLIST fasilitas
    xmlns CDATA #FIXED ''>

<!ELEMENT jenis_kamar (#PCDATA)>
<!ATTLIST jenis_kamar
    xmlns CDATA #FIXED ''>

<!ELEMENT AC (#PCDATA)>
<!ATTLIST AC
    xmlns CDATA #FIXED ''>

<!ELEMENT kamar_mandi (#PCDATA)>
<!ATTLIST kamar_mandi
    xmlns CDATA #FIXED ''>

<!ELEMENT TV (#PCDATA)>
<!ATTLIST TV
    xmlns CDATA #FIXED ''>

<!ELEMENT tempat_tidur (#PCDATA)>
<!ATTLIST tempat_tidur
    xmlns CDATA #FIXED ''>

<!ELEMENT sofa (#PCDATA)>
<!ATTLIST sofa
    xmlns CDATA #FIXED ''>

<!ELEMENT meja (#PCDATA)>
<!ATTLIST meja
    xmlns CDATA #FIXED ''>

<!ELEMENT pengering_rambut (#PCDATA)>
<!ATTLIST pengering_rambut
    xmlns CDATA #FIXED ''>

<!ELEMENT mesin_pembuat_kopi (#PCDATA)>
<!ATTLIST mesin_pembuat_kopi
    xmlns CDATA #FIXED ''>

<!ELEMENT ruang_tamu (#PCDATA)>
<!ATTLIST ruang_tamu
    xmlns CDATA #FIXED ''>

<!ELEMENT ukuran_ruangan (#PCDATA)>
<!ATTLIST ukuran_ruangan
    xmlns CDATA #FIXED ''>

=== hannaat/tugas-xml-dan-dtd/tugas.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE hotel SYSTEM "hotel.dtd">
<hotel>
<Kamar>
  <kode>101</kode>
  <lantai>1</lantai>
  <harga>250000</harga>
  <fasilitas>
     <AC>1</AC>
     <kamar_mandi>1</kamar_mandi>
     <TV>1</TV>
     <tempat_tidur>1</tempat_tidur>
     <meja>2</meja>
     <ukuran_ruangan>kecil</ukuran_ruangan>
  </fasilitas>
  <jenis_kamar>standard_room</jenis_kamar>
</Kamar>  
 
<Kamar>
  <kode>201</kode>
  <lantai>2</lantai>
  <harga>500000</harga>
  <fasilitas>
     <AC>1</AC>
     <kamar_mandi>1</kamar_mandi>
     <TV>1</TV>
     <tempat_tidur>1</tempat_tidur>
     <sofa>1</sofa>
     <meja>1</meja>
     <pengering_rambut>1</pengering_rambut>
     <mesin_pembuat_kopi>1</mesin_pembuat_kopi>
  	 <ukuran_ruangan>sedang</ukuran_ruangan>
  </fasilitas>
  <jenis_kamar>superior_room</jenis_kamar>
</Kamar> 

<Kamar>
  <kode>301</kode>
  <lantai>3</lantai>
  <harga>1250000</harga>
  <fasilitas>
     <AC>1</AC>
     <kamar_mandi>1</kamar_mandi>
     <TV>1</TV>
     <tempat_tidur>1</tempat_tidur>
     <sofa>1</sofa>
     <meja>1</meja>
     <pengering_rambut>1</pengering_rambut>
     <mesin_pembuat_kopi>1</mesin_pembuat_kopi>
     <ukuran_ruangan>besar</ukuran_ruangan>
  </fasilitas>
  <jenis_kamar>deluxe_room</jenis_kamar>
</Kamar> 
<Kamar>
  <kode>108</kode>
  <lantai>1</lantai>
  <harga>5000000</harga>
  <fasilitas>
     <AC>1</AC>
     <kamar_mandi>1</kamar_mandi>
     <TV>1</TV>
     <tempat_tidur>1</tempat_tidur>
     <sofa>1</sofa>
     <meja>1</meja>
     <pengering_rambut>1</pengering_rambut>
     <mesin_pembuat_kopi>1</mesin_pembuat_kopi>
     <ruang_tamu>1</ruang_tamu>
     <ukuran_ruangan>lebih besar</ukuran_ruangan>
  </fasilitas>
  <jenis_kamar>Suite</jenis_kamar>
</Kamar>
</hotel>
